#!/bin/bash

OUTPUT_HEADER="sweph_alias.h"
HEADERS=("swephexp.h" "sweph.h")

echo "// Autogenerated alias header for Parabola TPE" > "$OUTPUT_HEADER"
echo "#ifndef SWEPH_ALIAS_H" >> "$OUTPUT_HEADER"
echo "#define SWEPH_ALIAS_H" >> "$OUTPUT_HEADER"
echo "" >> "$OUTPUT_HEADER"
echo "#include \"parabola_wrapper.h\"" >> "$OUTPUT_HEADER"
echo "" >> "$OUTPUT_HEADER"

for header in "${HEADERS[@]}"; do
    if [[ -f "$header" ]]; then
        echo "// Aliases from $header" >> "$OUTPUT_HEADER"

        cat "$header" \
        | grep -oE 'swe_[a-zA-Z0-9_]+' \
        | sort -u \
        | while read -r func; do
            echo "#define $func parabola_$func" >> "$OUTPUT_HEADER"
        done

        echo "" >> "$OUTPUT_HEADER"
    else
        echo "⚠️  Warning: $header not found, skipping."
    fi
done

echo "#endif // SWEPH_ALIAS_H" >> "$OUTPUT_HEADER"

echo "✅ Generated $OUTPUT_HEADER from: ${HEADERS[*]}"
