# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/reed/reeddev/parabola_cpp/swisseph

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/reed/reeddev/parabola_cpp/swisseph

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reed/reeddev/parabola_cpp/swisseph/CMakeFiles /home/reed/reeddev/parabola_cpp/swisseph//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reed/reeddev/parabola_cpp/swisseph/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named swe

# Build rule for target.
swe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swe
.PHONY : swe

# fast build rule for target.
swe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/build
.PHONY : swe/fast

#=============================================================================
# Target rules for targets named parabola_wrapper

# Build rule for target.
parabola_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parabola_wrapper
.PHONY : parabola_wrapper

# fast build rule for target.
parabola_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/build
.PHONY : parabola_wrapper/fast

#=============================================================================
# Target rules for targets named parabola_tuner

# Build rule for target.
parabola_tuner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parabola_tuner
.PHONY : parabola_tuner

# fast build rule for target.
parabola_tuner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/build
.PHONY : parabola_tuner/fast

parabola_wrapper.o: parabola_wrapper.cpp.o
.PHONY : parabola_wrapper.o

# target to build an object file
parabola_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_wrapper.cpp.o
.PHONY : parabola_wrapper.cpp.o

parabola_wrapper.i: parabola_wrapper.cpp.i
.PHONY : parabola_wrapper.i

# target to preprocess a source file
parabola_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_wrapper.cpp.i
.PHONY : parabola_wrapper.cpp.i

parabola_wrapper.s: parabola_wrapper.cpp.s
.PHONY : parabola_wrapper.s

# target to generate assembly for a file
parabola_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_wrapper.cpp.s
.PHONY : parabola_wrapper.cpp.s

swecl.o: swecl.c.o
.PHONY : swecl.o

# target to build an object file
swecl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.c.o
.PHONY : swecl.c.o

swecl.i: swecl.c.i
.PHONY : swecl.i

# target to preprocess a source file
swecl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.c.i
.PHONY : swecl.c.i

swecl.s: swecl.c.s
.PHONY : swecl.s

# target to generate assembly for a file
swecl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.c.s
.PHONY : swecl.c.s

swedate.o: swedate.c.o
.PHONY : swedate.o

# target to build an object file
swedate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.c.o
.PHONY : swedate.c.o

swedate.i: swedate.c.i
.PHONY : swedate.i

# target to preprocess a source file
swedate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.c.i
.PHONY : swedate.c.i

swedate.s: swedate.c.s
.PHONY : swedate.s

# target to generate assembly for a file
swedate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.c.s
.PHONY : swedate.c.s

swehel.o: swehel.c.o
.PHONY : swehel.o

# target to build an object file
swehel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.c.o
.PHONY : swehel.c.o

swehel.i: swehel.c.i
.PHONY : swehel.i

# target to preprocess a source file
swehel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.c.i
.PHONY : swehel.c.i

swehel.s: swehel.c.s
.PHONY : swehel.s

# target to generate assembly for a file
swehel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.c.s
.PHONY : swehel.c.s

swehouse.o: swehouse.c.o
.PHONY : swehouse.o

# target to build an object file
swehouse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.c.o
.PHONY : swehouse.c.o

swehouse.i: swehouse.c.i
.PHONY : swehouse.i

# target to preprocess a source file
swehouse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.c.i
.PHONY : swehouse.c.i

swehouse.s: swehouse.c.s
.PHONY : swehouse.s

# target to generate assembly for a file
swehouse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.c.s
.PHONY : swehouse.c.s

swejpl.o: swejpl.c.o
.PHONY : swejpl.o

# target to build an object file
swejpl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.c.o
.PHONY : swejpl.c.o

swejpl.i: swejpl.c.i
.PHONY : swejpl.i

# target to preprocess a source file
swejpl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.c.i
.PHONY : swejpl.c.i

swejpl.s: swejpl.c.s
.PHONY : swejpl.s

# target to generate assembly for a file
swejpl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.c.s
.PHONY : swejpl.c.s

swemmoon.o: swemmoon.c.o
.PHONY : swemmoon.o

# target to build an object file
swemmoon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.c.o
.PHONY : swemmoon.c.o

swemmoon.i: swemmoon.c.i
.PHONY : swemmoon.i

# target to preprocess a source file
swemmoon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.c.i
.PHONY : swemmoon.c.i

swemmoon.s: swemmoon.c.s
.PHONY : swemmoon.s

# target to generate assembly for a file
swemmoon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.c.s
.PHONY : swemmoon.c.s

swemplan.o: swemplan.c.o
.PHONY : swemplan.o

# target to build an object file
swemplan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.c.o
.PHONY : swemplan.c.o

swemplan.i: swemplan.c.i
.PHONY : swemplan.i

# target to preprocess a source file
swemplan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.c.i
.PHONY : swemplan.c.i

swemplan.s: swemplan.c.s
.PHONY : swemplan.s

# target to generate assembly for a file
swemplan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.c.s
.PHONY : swemplan.c.s

sweph.o: sweph.c.o
.PHONY : sweph.o

# target to build an object file
sweph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.c.o
.PHONY : sweph.c.o

sweph.i: sweph.c.i
.PHONY : sweph.i

# target to preprocess a source file
sweph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.c.i
.PHONY : sweph.c.i

sweph.s: sweph.c.s
.PHONY : sweph.s

# target to generate assembly for a file
sweph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.c.s
.PHONY : sweph.c.s

swephlib.o: swephlib.c.o
.PHONY : swephlib.o

# target to build an object file
swephlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.c.o
.PHONY : swephlib.c.o

swephlib.i: swephlib.c.i
.PHONY : swephlib.i

# target to preprocess a source file
swephlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.c.i
.PHONY : swephlib.c.i

swephlib.s: swephlib.c.s
.PHONY : swephlib.s

# target to generate assembly for a file
swephlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.c.s
.PHONY : swephlib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... parabola_tuner"
	@echo "... parabola_wrapper"
	@echo "... swe"
	@echo "... parabola_wrapper.o"
	@echo "... parabola_wrapper.i"
	@echo "... parabola_wrapper.s"
	@echo "... swecl.o"
	@echo "... swecl.i"
	@echo "... swecl.s"
	@echo "... swedate.o"
	@echo "... swedate.i"
	@echo "... swedate.s"
	@echo "... swehel.o"
	@echo "... swehel.i"
	@echo "... swehel.s"
	@echo "... swehouse.o"
	@echo "... swehouse.i"
	@echo "... swehouse.s"
	@echo "... swejpl.o"
	@echo "... swejpl.i"
	@echo "... swejpl.s"
	@echo "... swemmoon.o"
	@echo "... swemmoon.i"
	@echo "... swemmoon.s"
	@echo "... swemplan.o"
	@echo "... swemplan.i"
	@echo "... swemplan.s"
	@echo "... sweph.o"
	@echo "... sweph.i"
	@echo "... sweph.s"
	@echo "... swephlib.o"
	@echo "... swephlib.i"
	@echo "... swephlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

