# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/reed/reeddev/parabola_cpp/swisseph

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/reed/reeddev/parabola_cpp/swisseph

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reed/reeddev/parabola_cpp/swisseph/CMakeFiles /home/reed/reeddev/parabola_cpp/swisseph//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reed/reeddev/parabola_cpp/swisseph/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named swe

# Build rule for target.
swe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swe
.PHONY : swe

# fast build rule for target.
swe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/build
.PHONY : swe/fast

#=============================================================================
# Target rules for targets named parabola_wrapper

# Build rule for target.
parabola_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parabola_wrapper
.PHONY : parabola_wrapper

# fast build rule for target.
parabola_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/build
.PHONY : parabola_wrapper/fast

#=============================================================================
# Target rules for targets named parabola_tester

# Build rule for target.
parabola_tester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parabola_tester
.PHONY : parabola_tester

# fast build rule for target.
parabola_tester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tester.dir/build.make CMakeFiles/parabola_tester.dir/build
.PHONY : parabola_tester/fast

#=============================================================================
# Target rules for targets named parabola_tuner

# Build rule for target.
parabola_tuner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parabola_tuner
.PHONY : parabola_tuner

# fast build rule for target.
parabola_tuner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/build
.PHONY : parabola_tuner/fast

# target to build an object file
parabola_tester.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tester.dir/build.make CMakeFiles/parabola_tester.dir/parabola_tester.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_tester.o
.PHONY : parabola_tester.o

# target to preprocess a source file
parabola_tester.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tester.dir/build.make CMakeFiles/parabola_tester.dir/parabola_tester.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_tester.i
.PHONY : parabola_tester.i

# target to generate assembly for a file
parabola_tester.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tester.dir/build.make CMakeFiles/parabola_tester.dir/parabola_tester.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_tuner.dir/build.make CMakeFiles/parabola_tuner.dir/parabola_tester.s
.PHONY : parabola_tester.s

# target to build an object file
parabola_wrapper.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.o
.PHONY : parabola_wrapper.o

# target to preprocess a source file
parabola_wrapper.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.i
.PHONY : parabola_wrapper.i

# target to generate assembly for a file
parabola_wrapper.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parabola_wrapper.dir/build.make CMakeFiles/parabola_wrapper.dir/parabola_wrapper.s
.PHONY : parabola_wrapper.s

# target to build an object file
swecl.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.o
.PHONY : swecl.o

# target to preprocess a source file
swecl.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.i
.PHONY : swecl.i

# target to generate assembly for a file
swecl.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swecl.s
.PHONY : swecl.s

# target to build an object file
swedate.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.o
.PHONY : swedate.o

# target to preprocess a source file
swedate.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.i
.PHONY : swedate.i

# target to generate assembly for a file
swedate.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swedate.s
.PHONY : swedate.s

# target to build an object file
swehel.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.o
.PHONY : swehel.o

# target to preprocess a source file
swehel.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.i
.PHONY : swehel.i

# target to generate assembly for a file
swehel.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehel.s
.PHONY : swehel.s

# target to build an object file
swehouse.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.o
.PHONY : swehouse.o

# target to preprocess a source file
swehouse.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.i
.PHONY : swehouse.i

# target to generate assembly for a file
swehouse.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swehouse.s
.PHONY : swehouse.s

# target to build an object file
swejpl.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.o
.PHONY : swejpl.o

# target to preprocess a source file
swejpl.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.i
.PHONY : swejpl.i

# target to generate assembly for a file
swejpl.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swejpl.s
.PHONY : swejpl.s

# target to build an object file
swemmoon.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.o
.PHONY : swemmoon.o

# target to preprocess a source file
swemmoon.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.i
.PHONY : swemmoon.i

# target to generate assembly for a file
swemmoon.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemmoon.s
.PHONY : swemmoon.s

# target to build an object file
swemplan.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.o
.PHONY : swemplan.o

# target to preprocess a source file
swemplan.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.i
.PHONY : swemplan.i

# target to generate assembly for a file
swemplan.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swemplan.s
.PHONY : swemplan.s

# target to build an object file
sweph.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.o
.PHONY : sweph.o

# target to preprocess a source file
sweph.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.i
.PHONY : sweph.i

# target to generate assembly for a file
sweph.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/sweph.s
.PHONY : sweph.s

# target to build an object file
swephlib.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.o
.PHONY : swephlib.o

# target to preprocess a source file
swephlib.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.i
.PHONY : swephlib.i

# target to generate assembly for a file
swephlib.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/swe.dir/build.make CMakeFiles/swe.dir/swephlib.s
.PHONY : swephlib.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... parabola_tester"
	@echo "... parabola_tuner"
	@echo "... parabola_wrapper"
	@echo "... swe"
	@echo "... parabola_tester.o"
	@echo "... parabola_tester.i"
	@echo "... parabola_tester.s"
	@echo "... parabola_wrapper.o"
	@echo "... parabola_wrapper.i"
	@echo "... parabola_wrapper.s"
	@echo "... swecl.o"
	@echo "... swecl.i"
	@echo "... swecl.s"
	@echo "... swedate.o"
	@echo "... swedate.i"
	@echo "... swedate.s"
	@echo "... swehel.o"
	@echo "... swehel.i"
	@echo "... swehel.s"
	@echo "... swehouse.o"
	@echo "... swehouse.i"
	@echo "... swehouse.s"
	@echo "... swejpl.o"
	@echo "... swejpl.i"
	@echo "... swejpl.s"
	@echo "... swemmoon.o"
	@echo "... swemmoon.i"
	@echo "... swemmoon.s"
	@echo "... swemplan.o"
	@echo "... swemplan.i"
	@echo "... swemplan.s"
	@echo "... sweph.o"
	@echo "... sweph.i"
	@echo "... sweph.s"
	@echo "... swephlib.o"
	@echo "... swephlib.i"
	@echo "... swephlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

